# Generated by Django 4.2.19 on 2025-02-25 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_trainingjob_dataset_path_trainingjob_task_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "prompt_template",
                    models.TextField(
                        blank=True,
                        help_text="Template for prompts to include character's style",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Agent",
                "verbose_name_plural": "AI Agents",
            },
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="agent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_job",
                to="chat.agentmodel",
            ),
        ),
    ]
