import type { Metadata } from "next";
import { Providers } from "./providers";
import "@/styles/globals.scss";
import { ClientLayout } from "./client-layout";

export const metadata: Metadata = {
  title: "Playarts - AI Agent",
  description: "Generated by create next app",
  icons: {
    icon: "images/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ClientLayout>{children}</ClientLayout>
        </Providers>
      </body>
    </html>
  );
}
